// <auto-generated />
using System;
using Kawerk.Infastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kawerk.Migrations
{
    [DbContext(typeof(DbBase))]
    [Migration("20251127220413_ImportantTweaksToNullability")]
    partial class ImportantTweaksToNullability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kawerk.Domain.Entities.Branches", b =>
                {
                    b.Property<Guid>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Warranty")
                        .HasColumnType("varchar(200)");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Warranty")
                        .HasColumnType("varchar(200)");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Salesman", b =>
                {
                    b.Property<Guid>("SalesmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("BranchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("SalesmanID");

                    b.HasIndex("BranchID");

                    b.ToTable("Salesman");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("BuyerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SellerCustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SellerManufacturerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("SellerCustomerID");

                    b.HasIndex("SellerManufacturerID");

                    b.HasIndex("VehicleID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchesBranchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EngineCapacity")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FuelType")
                        .HasColumnType("varchar(100)");

                    b.PrimitiveCollection<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Transmission")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Year")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("VehicleID");

                    b.HasIndex("BranchesBranchID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Salesman", b =>
                {
                    b.HasOne("Kawerk.Domain.Entities.Branches", "Branch")
                        .WithMany("Salesmen")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Kawerk.Domain.Entities.Customer", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kawerk.Domain.Entities.Customer", "SellerCustomer")
                        .WithMany("Sells")
                        .HasForeignKey("SellerCustomerID");

                    b.HasOne("Kawerk.Domain.Entities.Manufacturer", "SellerManufacturer")
                        .WithMany("Transactions")
                        .HasForeignKey("SellerManufacturerID");

                    b.HasOne("Kawerk.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("Transaction")
                        .HasForeignKey("Kawerk.Domain.Entities.Transaction", "VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("SellerCustomer");

                    b.Navigation("SellerManufacturer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Kawerk.Domain.Entities.Branches", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("BranchesBranchID");

                    b.HasOne("Kawerk.Domain.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Kawerk.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Branches", b =>
                {
                    b.Navigation("Salesmen");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sells");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
