// <auto-generated />
using System;
using Kawerk.Infastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kawerk.Migrations
{
    [DbContext(typeof(DbBase))]
    [Migration("20251223110054_RefreshTokens")]
    partial class RefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerManufacturer", b =>
                {
                    b.Property<Guid>("SubscribedManufacturersManufacturerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscribersCustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubscribedManufacturersManufacturerID", "SubscribersCustomerID");

                    b.HasIndex("SubscribersCustomerID");

                    b.ToTable("CustomerManufacturer");
                });

            modelBuilder.Entity("Kawerk.Domain.Branches", b =>
                {
                    b.Property<Guid>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Warranty")
                        .HasColumnType("varchar(200)");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Kawerk.Domain.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AdministratorOf")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Kawerk.Domain.Manufacturer", b =>
                {
                    b.Property<Guid>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Warranty")
                        .HasColumnType("varchar(200)");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Kawerk.Domain.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CustomerID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Kawerk.Domain.RefreshTokens", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Kawerk.Domain.Salesman", b =>
                {
                    b.Property<Guid>("SalesmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("BranchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("SalesmanID");

                    b.HasIndex("BranchID");

                    b.ToTable("Salesman");
                });

            modelBuilder.Entity("Kawerk.Domain.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("BuyerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SellerCustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SellerManufacturerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("SellerCustomerID");

                    b.HasIndex("SellerManufacturerID");

                    b.HasIndex("VehicleID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Kawerk.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchesBranchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuyerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EngineCapacity")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FuelType")
                        .HasColumnType("varchar(100)");

                    b.PrimitiveCollection<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManufacturerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("SellerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Transmission")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Year")
                        .HasColumnType("varchar(100)");

                    b.HasKey("VehicleID");

                    b.HasIndex("BranchesBranchID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("SellerID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CustomerManufacturer", b =>
                {
                    b.HasOne("Kawerk.Domain.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("SubscribedManufacturersManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kawerk.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("SubscribersCustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kawerk.Domain.Notification", b =>
                {
                    b.HasOne("Kawerk.Domain.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kawerk.Domain.RefreshTokens", b =>
                {
                    b.HasOne("Kawerk.Domain.Customer", "Customer")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Kawerk.Domain.RefreshTokens", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kawerk.Domain.Salesman", b =>
                {
                    b.HasOne("Kawerk.Domain.Branches", "Branch")
                        .WithMany("Salesmen")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Kawerk.Domain.Transaction", b =>
                {
                    b.HasOne("Kawerk.Domain.Customer", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kawerk.Domain.Customer", "SellerCustomer")
                        .WithMany("Sells")
                        .HasForeignKey("SellerCustomerID");

                    b.HasOne("Kawerk.Domain.Manufacturer", "SellerManufacturer")
                        .WithMany("Transactions")
                        .HasForeignKey("SellerManufacturerID");

                    b.HasOne("Kawerk.Domain.Vehicle", "Vehicle")
                        .WithOne("Transaction")
                        .HasForeignKey("Kawerk.Domain.Transaction", "VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("SellerCustomer");

                    b.Navigation("SellerManufacturer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Kawerk.Domain.Vehicle", b =>
                {
                    b.HasOne("Kawerk.Domain.Branches", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("BranchesBranchID");

                    b.HasOne("Kawerk.Domain.Customer", "Buyer")
                        .WithMany("VehiclesBought")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kawerk.Domain.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kawerk.Domain.Customer", "Seller")
                        .WithMany("VehiclesSold")
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Buyer");

                    b.Navigation("Manufacturer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Kawerk.Domain.Branches", b =>
                {
                    b.Navigation("Salesmen");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Customer", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Purchases");

                    b.Navigation("RefreshToken");

                    b.Navigation("Sells");

                    b.Navigation("VehiclesBought");

                    b.Navigation("VehiclesSold");
                });

            modelBuilder.Entity("Kawerk.Domain.Manufacturer", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kawerk.Domain.Vehicle", b =>
                {
                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
